<?php
/*
 * block: \NewgenPayments\Helpers\Block\HelperBlock
 */
?>
<?php
$socialLinks  = $block->getNPConfig()->getSocialLinks();
if (!empty($socialLinks)) { 
?>
	<div class="social-links-container">
	<?php foreach($socialLinks as $sns => $link) {?>
	    <span class="social-link-item <?= $sns ?>">
			<a target="__blank" title="<?= ucfirst($sns) ?>" href="<?= $link ?>">
				<i class="ib ib-hover ic ic-lg ic-<?= $sns ?>"></i>
			</a>
	    </span>
	<?php } ?>
	</div>
<?php } ?>
